// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9Zn2Hn1Q3Mj_SmGyv1XN5kR8B7mb7XQQ',
    appId: '1:355406457835:web:8fbae14ec140ef06e247ae',
    messagingSenderId: '355406457835',
    projectId: 'expense-tracker-app-20bc8',
    authDomain: 'expense-tracker-app-20bc8.firebaseapp.com',
    storageBucket: 'expense-tracker-app-20bc8.firebasestorage.app',
    measurementId: 'G-QGQY1CG7TP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJkGzOEVNabmtJjKyTd0mfAOIycWdN6Jw',
    appId: '1:355406457835:android:d96f95078bc7ff31e247ae',
    messagingSenderId: '355406457835',
    projectId: 'expense-tracker-app-20bc8',
    storageBucket: 'expense-tracker-app-20bc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_3QSBoAVjA1ffOmJL4Lu2iEoJf5TCEto',
    appId: '1:355406457835:ios:96530589e99eb997e247ae',
    messagingSenderId: '355406457835',
    projectId: 'expense-tracker-app-20bc8',
    storageBucket: 'expense-tracker-app-20bc8.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_3QSBoAVjA1ffOmJL4Lu2iEoJf5TCEto',
    appId: '1:355406457835:ios:96530589e99eb997e247ae',
    messagingSenderId: '355406457835',
    projectId: 'expense-tracker-app-20bc8',
    storageBucket: 'expense-tracker-app-20bc8.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9Zn2Hn1Q3Mj_SmGyv1XN5kR8B7mb7XQQ',
    appId: '1:355406457835:web:bb75372d06c7adc1e247ae',
    messagingSenderId: '355406457835',
    projectId: 'expense-tracker-app-20bc8',
    authDomain: 'expense-tracker-app-20bc8.firebaseapp.com',
    storageBucket: 'expense-tracker-app-20bc8.firebasestorage.app',
    measurementId: 'G-PJLTHM5E84',
  );
}
